# Prettier Configuration for Sentry Maven Skin
# See: https://prettier.io/docs/en/options.html

# Use tabs for indentation (consistent with existing code style)
useTabs: true
tabWidth: 4

# Double quotes for strings (consistent with ESLint config)
singleQuote: false

# No trailing commas (better compatibility with older browsers)
trailingComma: "none"

# Print width
printWidth: 120

# Semicolons at the end of statements
semi: true

# Bracket spacing in object literals
bracketSpacing: true

# Put the > of a multi-line HTML element at the end of the last line
bracketSameLine: false

# Line endings: auto (CRLF on Windows, LF on Linux/macOS)
endOfLine: "auto"

# HTML whitespace sensitivity
htmlWhitespaceSensitivity: "css"

# Overrides for specific file types
overrides:
  - files: "*.css"
    options:
      singleQuote: false
  - files: "*.html"
    options:
      printWidth: 200
      htmlWhitespaceSensitivity: "ignore"
