sentry.tocHeadingText=On this Page
sentry.copyrightText=Copyright
sentry.publishDateText=Documentation as of
sentry.searchFieldText=Search...
sentry.searchResultsText=Search Results for
sentry.searchResultSingleText=result
sentry.searchResultCountText=results
sentry.projectVersionText=Version
