# This workflow releases the project on Maven Central
# and prepare a new development version

name: Release to Maven Central
run-name: Release v${{ inputs.releaseVersion }} to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
      developmentVersion:
        description: "New SNAPSHOT version"
        required: true

jobs:
  release:
    uses: sentrysoftware/workflows/.github/workflows/maven-central-release.yml@b79e9328c15e58bf66af4b1628d2f296a882e7ed # Node 24 actions, Ubuntu 24.04
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
      developmentVersion: ${{ inputs.developmentVersion }}
      autoRelease: true
      jdkVersion: "17"
      nodeVersion: "20.x"
    secrets: inherit
